load("@rules_cc//cc:defs.bzl", "cc_test")
load("//tool/bazel:fildesh_test.bzl", "fildesh_test")

cc_test(
    name = "append_test",
    srcs = ["append_test.c"],
    deps = ["//:sxproto_lib"],
)

cc_test(
    name = "assign_test",
    srcs = ["assign_test.c"],
    deps = ["//:sxproto_lib"],
)

cc_test(
    name = "create_test",
    srcs = ["create_test.c"],
    deps = ["//:sxproto_lib"],
)

cc_test(
    name = "parse_test",
    srcs = ["parse_test.c"],
    deps = ["//:sxproto_lib"],
)

cc_test(
    name = "parse_manyof_test",
    srcs = ["parse_manyof_test.c"],
    deps = ["//:sxproto_lib"],
)

cc_test(
    name = "parse_nest_test",
    srcs = ["parse_nest_test.c"],
    deps = ["//:sxproto_lib"],
)

cc_test(
    name = "parse_with_schema_test",
    srcs = ["parse_with_schema_test.c"],
    deps = ["//:sxproto_lib"],
)

cc_test(
    name = "print_sxpb_test",
    srcs = [
        "print_sxpb_test.c",
        "print_test.c",
        "print_test.h",
    ],
    args = ["test/sxproto/content/idempotent_sxpb2sxpb_test_dict.sxpb"],
    data = ["//test/sxproto/content:idempotent_sxpb2sxpb_test_dict.sxpb"],
    deps = ["//:sxproto_lib"],
)

cc_test(
    name = "print_content_test",
    srcs = [
        "print_content_test.c",
        "print_test.c",
        "print_test.h",
        "//test/sxproto/content:array.c",
        "//test/sxproto/content:dict.c",
        "//test/sxproto/content:loneof.c",
        "//test/sxproto/content:manyof.c",
        "//test/sxproto/content:message.c",
        "//test/sxproto/content:nest.c",
        "//test/sxproto/content:string.c",
    ],
    args = ["test/sxproto/content"],
    data = [
        "//test/sxproto/content:array.json",
        "//test/sxproto/content:array.txtpb",
        "//test/sxproto/content:array.yaml",
        "//test/sxproto/content:dict.json",
        "//test/sxproto/content:dict.txtpb",
        "//test/sxproto/content:dict.yaml",
        "//test/sxproto/content:loneof.json",
        "//test/sxproto/content:loneof.txtpb",
        "//test/sxproto/content:loneof.yaml",
        "//test/sxproto/content:manyof.json",
        "//test/sxproto/content:manyof.txtpb",
        "//test/sxproto/content:manyof.yaml",
        "//test/sxproto/content:message.json",
        "//test/sxproto/content:message.txtpb",
        "//test/sxproto/content:message.yaml",
        "//test/sxproto/content:nest.json",
        "//test/sxproto/content:nest.txtpb",
        "//test/sxproto/content:nest.yaml",
        "//test/sxproto/content:string.json",
        "//test/sxproto/content:string.txtpb",
        "//test/sxproto/content:string.yaml",
    ],
    deps = ["//:sxproto_lib"],
)

cc_test(
    name = "toplevel_test",
    srcs = ["toplevel_test.c"],
    deps = ["//:sxproto_lib"],
)

fildesh_test(
    name = "sxpb2json_test",
    srcs = ["sxpb2json_test.fildesh"],
    input_by_option = {
        "array_json": "//test/sxproto/content:array.json",
        "array_sxpb": "//test/sxproto/content:array.sxpb",
        "dict_json": "//test/sxproto/content:dict.json",
        "dict_sxpb": "//test/sxproto/content:dict.sxpb",
        "loneof_json": "//test/sxproto/content:loneof.json",
        "loneof_sxpb": "//test/sxproto/content:loneof.sxpb",
        "manyof_json": "//test/sxproto/content:manyof.json",
        "manyof_sxpb": "//test/sxproto/content:manyof.sxpb",
        "message_json": "//test/sxproto/content:message.json",
        "message_sxpb": "//test/sxproto/content:message.sxpb",
        "nest_json": "//test/sxproto/content:nest.json",
        "nest_sxpb": "//test/sxproto/content:nest.sxpb",
        "string_json": "//test/sxproto/content:string.json",
        "string_sxpb": "//test/sxproto/content:string.sxpb",
    },
)

fildesh_test(
    name = "sxpb2sxpb_test",
    srcs = ["sxpb2sxpb_test.fildesh"],
    input_by_option = {
        "array_json": "//test/sxproto/content:array.json",
        "array_sxpb": "//test/sxproto/content:array.sxpb",
        "dict_json": "//test/sxproto/content:dict.json",
        "dict_sxpb": "//test/sxproto/content:dict.sxpb",
        "loneof_json": "//test/sxproto/content:loneof.json",
        "loneof_sxpb": "//test/sxproto/content:loneof.sxpb",
        "manyof_json": "//test/sxproto/content:manyof.json",
        "manyof_sxpb": "//test/sxproto/content:manyof.sxpb",
        "message_json": "//test/sxproto/content:message.json",
        "message_sxpb": "//test/sxproto/content:message.sxpb",
        "nest_json": "//test/sxproto/content:nest.json",
        "nest_sxpb": "//test/sxproto/content:nest.sxpb",
        "string_json": "//test/sxproto/content:string.json",
        "string_sxpb": "//test/sxproto/content:string.sxpb",
    },
)

fildesh_test(
    name = "sxpb2txtpb_test",
    srcs = ["sxpb2txtpb_test.fildesh"],
    input_by_option = {
        "array_sxpb": "//test/sxproto/content:array.sxpb",
        "array_txtpb": "//test/sxproto/content:array.txtpb",
        "dict_sxpb": "//test/sxproto/content:dict.sxpb",
        "dict_txtpb": "//test/sxproto/content:dict.txtpb",
        "loneof_sxpb": "//test/sxproto/content:loneof.sxpb",
        "loneof_txtpb": "//test/sxproto/content:loneof.txtpb",
        "manyof_sxpb": "//test/sxproto/content:manyof.sxpb",
        "manyof_txtpb": "//test/sxproto/content:manyof.txtpb",
        "message_sxpb": "//test/sxproto/content:message.sxpb",
        "message_txtpb": "//test/sxproto/content:message.txtpb",
        "string_sxpb": "//test/sxproto/content:string.sxpb",
        "string_txtpb": "//test/sxproto/content:string.txtpb",
    },
)

fildesh_test(
    name = "sxpb2yaml_test",
    srcs = ["sxpb2yaml_test.fildesh"],
    input_by_option = {
        "array_sxpb": "//test/sxproto/content:array.sxpb",
        "array_yaml": "//test/sxproto/content:array.yaml",
        "dict_sxpb": "//test/sxproto/content:dict.sxpb",
        "dict_yaml": "//test/sxproto/content:dict.yaml",
        "loneof_sxpb": "//test/sxproto/content:loneof.sxpb",
        "loneof_yaml": "//test/sxproto/content:loneof.yaml",
        "manyof_sxpb": "//test/sxproto/content:manyof.sxpb",
        "manyof_yaml": "//test/sxproto/content:manyof.yaml",
        "message_sxpb": "//test/sxproto/content:message.sxpb",
        "message_yaml": "//test/sxproto/content:message.yaml",
        "nest_sxpb": "//test/sxproto/content:nest.sxpb",
        "nest_yaml": "//test/sxproto/content:nest.yaml",
        "string_sxpb": "//test/sxproto/content:string.sxpb",
        "string_yaml": "//test/sxproto/content:string.yaml",
    },
)
