
exports_files([
    "args.txt",
    "args2.txt",
    "convoluted.txt",
    "cycle.txt",
    "familiar.txt",
    "hello.txt",
    "literal_0.txt",
    "literal_127.txt",
    "name.txt",
    "silly.txt",
    "test.txt",
    "xpipe_nested.txt",
])
