
cc_test(
    name = "getline_test",
    srcs = ["getline_test.c"],
    deps = ["//:lace_lib"],
    size = "small",
)

cc_test(
    name = "size_test",
    srcs = ["size_test.c"],
    deps = ["//:lace_lib"],
    size = "small",
)

