
cc_test(
    name = "delimit_edge_test",
    srcs = ["delimit_edge_test.c"],
    deps = ["//:lace_lib"],
    size = "small",
)

cc_test(
    name = "getline_test",
    srcs = ["getline_test.c"],
    deps = ["//:lace_lib"],
    size = "small",
)

cc_test(
    name = "gets_test",
    srcs = ["gets_test.c"],
    deps = ["//:lace_lib"],
    size = "small",
)

cc_test(
    name = "read_file_lines_test",
    data = ["read_file_lines_test.c"],
    srcs = ["read_file_lines_test.c"],
    deps = ["//:lace_lib"],
    size = "small",
)

cc_test(
    name = "size_test",
    srcs = ["size_test.c"],
    deps = ["//:lace_lib"],
    size = "small",
)

cc_test(
    name = "slicechrs_test",
    srcs = ["slicechrs_test.c"],
    deps = ["//:lace_lib"],
    size = "small",
)
