load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "sxproto_lib",
    srcs = [
        "parse_sxpb.c",
        "parse_sxpb.h",
        "schema.c",
        "sxpb.c",
        "syntax.h",
        "value.c",
        "value.h",
        "//include/fildesh:sxproto.h",
        "//src/sxproto/print:srcs",
    ],
    visibility = ["//:__pkg__"],
    deps = ["//:fildesh_lib"],
)
