
cc_test(
    name = "sh_escape_argv_test",
    srcs = ["sh_escape_argv_test.c"],
    deps = ["//:lace_compat_lib"],
)

cc_test(
    name = "string_byte_translate_test",
    srcs = ["string_byte_translate_test.c"],
    deps = ["//:lace_compat_lib"],
)
