exports_files([
    "fildesh.h",
    "fildesh_compat_errno.h",
    "fildesh_compat_fd.h",
    "fildesh_compat_file.h",
    "fildesh_compat_random.h",
    "fildesh_compat_sh.h",
    "fildesh_compat_string.h",
    "fildesh_posix_thread.h",
    "fildesh_tool.h",
])
exports_files([
    "fildesh_builtin.h",
], visibility = [
    "//src:__subpackages__",
    "//test:__subpackages__",
])
