name: Bazel
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v1
      with:
        bazel-version: '5.2.0'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Remove WORKSPACE.bazel content.
      run: sed -i -E -e 's/^.*$//' WORKSPACE.bazel

    - name: Build
      run: bazel build --config=bzlmod //...

    - name: Test
      # --enable_runfiles is for Windows tests to access data deps.
      run: bazel test --config=bzlmod --enable_runfiles --test_timeout 10 //...

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Test Results (${{ matrix.platform }})
        path: |
          bazel-testlogs*/**/test.log
          bazel-bin*/builtin/*
          bazel-bin*/src/*
          bazel-bin*/test/*
          bazel-bin*/tool/*
          !bazel-bin*/test/syntax/
          !bazel-bin*/**/_objs/
          !bazel-bin*/**/*.cppmap
          !bazel-bin*/**/*.params
          !bazel-bin*/**/*.runfiles*


  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v1
      with:
        bazel-version: '5.2.0'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: bazel build --config=bzlmod --config=benchmark --jobs=auto //test/benchmark/...
    - name: Benchmark
      run: bazel test --config=bzlmod --config=benchmark //test/benchmark/...


  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v1
      with:
        bazel-version: '5.2.0'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Coverage
      run: >
        bazel coverage
        --config=bzlmod
        --instrument_test_targets
        --instrumentation_filter="^//..."
        --combined_report=lcov
        --
        //...
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: bazel-out/_coverage/_coverage_report.dat


  fuzz:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v1
      with:
        bazel-version: '5.2.0'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fuzz
      run: bazel test --config=bzlmod --config=asan-libfuzzer //test/fuzz/...


  test_without_bzlmod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v1
      with:
        bazel-version: '4.2.2'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: bazel test --test_timeout 10 //...
