name: Bazel
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v1
      with:
        bazel-version: '4.1.0'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: bazel build //...

    - name: Test
      # --enable_runfiles is for Windows tests to access data deps.
      run: bazel test --enable_runfiles --test_timeout 10 //...

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Test Results (${{ matrix.platform }})
        path: |
          bazel-bin*/builtin/*
          bazel-bin*/src/*
          bazel-bin*/test/*
          bazel-bin*/tool/*
          !bazel-bin*/**/_objs/
          !bazel-bin*/**/*.cppmap
          !bazel-bin*/**/*.params
          !bazel-bin*/**/*.runfiles*
          bazel-testlogs*/**/test.log
