name: Benchmark
on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v1
      with:
        bazel-version: '4.1.0'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: bazel build --config=benchmark --jobs=auto //test/benchmark/...

    - name: Benchmark
      run: bazel test --config=benchmark //test/benchmark/...
