name: CMake
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            cmake_build_type: RelOnHost
          - platform: macos-latest
            cmake_build_type: RelOnHost
          - platform: windows-latest
            cmake_build_type: Release

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/bld

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{runner.workspace}}/bld
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.cmake_build_type}}

    - name: Build
      working-directory: ${{runner.workspace}}/bld
      shell: bash
      run: cmake --build . --config ${{matrix.cmake_build_type}}

    - name: Test
      working-directory: ${{runner.workspace}}/bld
      shell: bash
      run: ctest --timeout 10 -C ${{matrix.cmake_build_type}}

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Test Results (${{ matrix.platform }})
        path: |
          ${{runner.workspace}}/bld/Testing/
          ${{runner.workspace}}/bld/builtin/RelOnHost/
          ${{runner.workspace}}/bld/src/RelOnHost/
          ${{runner.workspace}}/bld/test/*/RelOnHost/
          ${{runner.workspace}}/bld/tool/RelOnHost/


  configure_with_old_cmake:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: CMake Version Set
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '2.8.12'

    - name: CMake Version Get
      run: cmake --version

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/bld

    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/bld
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=RelOnHost
