---
name: "Manual Lint"
on: [push, pull_request]

jobs:
  lint:
    name: Manual Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install TinyCC
      run: sudo apt update && sudo apt -y install tcc

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/bld/pkg

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/bld
      run: >
        cmake $GITHUB_WORKSPACE
        -DCMAKE_C_COMPILER=tcc
        -DCMAKE_BUILD_TYPE=RelOnHost
        -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/bld/pkg

    - name: Build Fildesh
      working-directory: ${{runner.workspace}}/bld
      run: |
        cmake --build "."
        cmake -D "COMPONENT:STRING=bin" -P "cmake_install.cmake"

    - name: Lint
      run: >
        ${{runner.workspace}}/bld/pkg/bin/fildesh
        test/manual/lint.fildesh
