---
name: Docker Image

on:
  push:
    branches: ['deploy']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
    - name: Bazel Setup
      uses: jwlawson/actions-setup-bazel@v1
      with:
        bazel-version: '6'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Remove WORKSPACE.bazel content.
      run: sed -i -E -e 's/^.*$//' WORKSPACE.bazel

    - name: Build
      run: bazel build -c opt //:fildesh

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Image
      uses: docker/build-push-action@v4
      with:
        context: bazel-bin/
        file: pkg/docker/Dockerfile
        push: true
        tags: ghcr.io/fildesh/fildesh:latest

