---
# Find more information at:
# https://github.com/microsoft/msvc-code-analysis-action

name: "MSVC Analysis"

on:
  push:
    branches: ["trunk", "stage"]
  pull_request:
    branches: ["trunk", "stage"]
  schedule:
    - cron: '18 23 * * 1'

env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}/build'
  config: 'Debug'

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{ env.build }} -DCMAKE_BUILD_TYPE=${{ env.config }}

      - name: Run MSVC Code Analysis
        uses: microsoft/msvc-code-analysis-action@v0.1.1
        id: run-analysis
        with:
          cmakeBuildDirectory: ${{ env.build }}
          buildConfiguration: ${{ env.config }}
          ruleset: NativeRecommendedRules.ruleset
          ignoredPaths: ${{ github.workspace }}/src;${{ github.workspace }}/test;${{ github.workspace }}/tool

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}

      - name: Upload SARIF as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sarif-file
          path: ${{ steps.run-analysis.outputs.sarif }}

