---
name: Bazel
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: ubuntu-latest
          bazel_build_optstr: --config=linux_test_platform
          bazel_test_argstr: -- //...
        - platform: macos-latest
          bazel_build_optstr: --config=macos_test_platform
          bazel_test_argstr: -- //...
        - platform: windows-latest
          bazel_build_optstr: --config=windows_test_platform
          # For Windows, we need --enable_runfiles to access data deps.
          bazel_test_argstr: >
            --enable_runfiles
            --
            //...

    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Cache Setup
      uses: actions/cache@v5
      id: cache-bazel
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel

    - name: Bazel Setup
      uses: jwlawson/actions-setup-bazel@v2
      with:
        bazel-version: latest

    - name: Checkout
      uses: actions/checkout@v6

    - name: Build
      run: >
        bazel build
        ${{ matrix.bazel_build_optstr }}
        //...

    - name: Test
      run: >
        bazel test
        ${{ matrix.bazel_build_optstr }}
        --test_timeout 10
        ${{ matrix.bazel_test_argstr }}

    - name: Upload Test Results
      uses: actions/upload-artifact@v6
      if: failure()
      with:
        name: failure-${{ matrix.platform }}
        path: |
          bazel-testlogs*/**/test.log
          bazel-bin*/src/*
          bazel-bin*/test/*
          bazel-bin*/tool/*
          !bazel-bin*/test/syntax/
          !bazel-bin*/**/_objs/
          !bazel-bin*/**/*.cppmap
          !bazel-bin*/**/*.params
          !bazel-bin*/**/*.runfiles*


  test_with_oldish_bazel:
    runs-on: ubuntu-latest
    steps:
    - name: Bazel Setup
      uses: jwlawson/actions-setup-bazel@v2
      with:
        bazel-version: "6"
    - name: Checkout
      uses: actions/checkout@v6
    - name: Test
      run: >
        bazel test
        --experimental_enable_bzlmod
        -- //...


  test_with_old_bazel:
    runs-on: ubuntu-latest
    steps:
    - name: Bazel Setup
      uses: jwlawson/actions-setup-bazel@v2
      with:
        bazel-version: "5.4.1"
    - name: Checkout
      uses: actions/checkout@v6
    - name: Prepare
      run: touch WORKSPACE
    - name: Test
      run: >
        bazel test
        --check_direct_dependencies=error
        --experimental_enable_bzlmod
        --ignore_dev_dependency
        -- //... -//test/benchmark/...


  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Cache Setup
      uses: actions/cache@v5
      id: cache-bazel
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel
    - name: Bazel Setup
      uses: jwlawson/actions-setup-bazel@v2
      with:
        bazel-version: latest
    - name: Checkout
      uses: actions/checkout@v6
    - name: Build
      run: >
        bazel build --config=linux_test_platform
        --jobs=auto
        --config=benchmark //test/benchmark/...
    - name: Benchmark
      run: >
        bazel test --config=linux_test_platform
        --config=benchmark //test/benchmark/...


  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Cache Setup
      uses: actions/cache@v5
      id: cache-bazel
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel
    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v2
      with:
        bazel-version: latest
    - name: Checkout
      uses: actions/checkout@v6
    - name: Coverage
      run: >
        bazel coverage --config=linux_test_platform
        --instrument_test_targets
        --instrumentation_filter="^//..."
        --combined_report=lcov
        --
        //...
    - name: Strip Branch Coverage
      # Bazel 7 generates branch coverage, but we prefer line coverage reports.
      run: sed -i '/^BR/d' bazel-out/_coverage/_coverage_report.dat
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: bazel-out/_coverage/_coverage_report.dat


  fuzz:
    runs-on: ubuntu-latest
    steps:
    - name: Bazel Setup
      uses: jwlawson/actions-setup-bazel@v2
      with:
        bazel-version: latest
    - name: Checkout
      uses: actions/checkout@v6
    - name: Fuzz
      run: >
        bazel test --config=linux_test_platform
        --config=asan-libfuzzer
        //test/fuzz/...
